apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: tva
type: Opaque
stringData:
  # [.env] 파일을 보고 실제 값을 따옴표 안에 넣어주세요!
  UPSTAGE_API_KEY: "여기에_실제_키_입력"
  JWT_SECRET_KEY: "여기에_실제_키_입력"
  DB_PASSWORD: "여기에_실제_DB_비번_입력"