# app/agents/synthesizer/guards.py
from typing import List
from app.schemas.vector_hit import VectorHit


class GuardError(ValueError):
    pass


def validate_hits(hits: List[VectorHit]) -> None:
    """
    근거 데이터가 보고서를 생성하기에 충분한지 검증합니다.

    정책(Report Agent 강화):
    - hits가 비어있는 경우: 예외를 던지지 않고 통과시킵니다.
      (assembler가 cannot_say_report 스키마를 유지한 채 생성하도록 위임)
    - hits가 존재하는 경우: claim_text/evidence 필수 검증
    """
    if not hits:
        print("[Guards] hits is empty -> allow (cannot_say_report will be generated by assembler).")
        return

    for h in hits:
        if not (h.claim_text or "").strip():
            raise GuardError(f"주장 내용이 비어 있습니다 (ID: {h.claim_id})")
        if not h.evidence:
            raise GuardError(f"근거 데이터가 없습니다 (ID: {h.claim_id})")

    print("[Guards] All hits validated successfully.")
